#! /bin/sh
### BEGIN INIT INFO
# Provides:          string-tx_init
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for string-tx.
# Description:       Configures GPIO for string-tx.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio64/direction
	echo -n "0" > /sys/class/gpio/gpio64/value

	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio76/direction
	echo -n "0" > /sys/class/gpio/gpio76/value

	if [ ! -d /sys/class/gpio/gpio62 ] ; then
	    echo -n "62" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio62/direction
	chgrp gpio /sys/class/gpio/gpio62/value
	chmod g+rw /sys/class/gpio/gpio62/value

  # gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction

  chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
  chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
  chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
  chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale

  chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_en
  chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_en

  chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en

  chgrp adc /sys/bus/iio/devices/iio:device0/buffer/enable
  chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
  chgrp adc /sys/bus/iio/devices/iio:device0/buffer/length
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length

	modprobe iio-trig-hrtimer
 	echo -n "0" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger

  chgrp adc /sys/bus/iio/devices/trigger0/frequency
  chmod g+rw /sys/bus/iio/devices/trigger0/frequency

  chgrp adc /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger

	chgrp adc /dev/iio:device0
	chmod g+r /dev/iio:device0

	;;
    stop)

	echo -n "in" > /sys/class/gpio/gpio62/direction
	echo -n "62" > /sys/class/gpio/unexport
	echo -n "76" > /sys/class/gpio/unexport
	echo -n "64" > /sys/class/gpio/unexport

  echo -n "49" > /sys/class/gpio/unexport

	;;
    status)
    	ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
