#! /bin/sh
### BEGIN INIT INFO
# Provides:          lcdbutton_init
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures the Galileo shield pins for lcdbutton example.
# Description:       Configures the Galileo shield pins for lcdbutton example.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

  # IO3 = pwm1
  if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
    echo -n "1" > /sys/class/pwm/pwmchip0/export
  fi
  chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
  chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
  chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
  chmod g+w /sys/class/pwm/pwmchip0/pwm1/duty_cycle
  chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
  chmod g+w /sys/class/pwm/pwmchip0/pwm1/enable

      # gpio16 = 0 = out
  if [ ! -d /sys/class/gpio/gpio16 ] ; then
    echo -n "16" > /sys/class/gpio/export
  fi
  echo -n "out" > /sys/class/gpio/gpio16/direction
  echo -n "0" > /sys/class/gpio/gpio16/value

      # gpio17 = in = no pull-up nor pull-down
  if [ ! -d /sys/class/gpio/gpio17 ] ; then
    echo -n "17" > /sys/class/gpio/export
  fi
  echo -n "in" > /sys/class/gpio/gpio17/direction

      # gpio76 = 0
  if [ ! -d /sys/class/gpio/gpio76 ] ; then
    echo -n "76" > /sys/class/gpio/export
  fi
  echo -n "0" > /sys/class/gpio/gpio76/value

      # gpio64 = 1 */
  if [ ! -d /sys/class/gpio/gpio64 ] ; then
    echo -n "64" > /sys/class/gpio/export
  fi
  echo -n "1" > /sys/class/gpio/gpio64/value

  # enable button
  if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio6/direction

	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio36/direction
	echo -n "1" > /sys/class/gpio/gpio36/value

  if [ ! -d /sys/class/gpio/gpio37 ] ; then
      echo -n "37" > /sys/class/gpio/export
  fi
  echo -n "in" > /sys/class/gpio/gpio37/direction

	chgrp gpio /sys/class/gpio/gpio62/value
	chmod g+r /sys/class/gpio/gpio62/value

	# Pull-up on IO18
	if [ ! -d /sys/class/gpio/gpio57 ] ; then
    		echo -n "57" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio57/direction
	echo "1" > /sys/class/gpio/gpio57/value

	# Select I2C on IO18 and IO19
	if [ ! -d /sys/class/gpio/gpio60 ] ; then
    		echo -n "60" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio60/direction
	echo "0" > /sys/class/gpio/gpio60/value

	# Pull-up on IO19
	if [ ! -d /sys/class/gpio/gpio59 ] ; then
    		echo -n "59" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio59/direction
	echo "1" > /sys/class/gpio/gpio59/value

	chgrp i2c /dev/i2c-0
	chmod g+rw /dev/i2c-0

	;;
    stop)
    	# No pull-up on IO18
	echo "in" > /sys/class/gpio/gpio57/direction
	ecbo "57" > /sys/class/gpio/unexport

	# GPIO on IO18 and IO19
	echo "1" > /sys/class/gpio/gpio60/value
	echo "60" > /sys/class/gpio/unexport

	# No pull-up on  IO19
	echo "in" > /sys/class/gpio/gpio59/direction
	echo "59" > /sys/class/gpio/unexport

  echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
  echo -n "76" > /sys/class/gpio/unexport
  echo -n "64" > /sys/class/gpio/unexport
  echo -n "17" > /sys/class/gpio/unexport
  echo -n "1" > /sys/class/gpio/gpio16/value
  echo -n "16" > /sys/class/gpio/unexport
  echo -n "1" > /sys/class/pwm/pwmchip0/unexport
  echo -n "6" > /sys/class/gpio/unexport
  echo -n "36" > /sys/class/gpio/unexport
  echo -n "37" > /sys/class/gpio/unexport
	;;
    status)
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
